#!/bin/bash
# File: parse_pikachu

NAME=$(jq -r '.name' data.json | sed 's/.*/\u&/')
HEIGHT=$(jq -r '.height' data.json | awk '{printf "%.1f", $1/10}')
WEIGHT=$(jq -r '.weight' data.json | awk '{printf "%.1f", $1/10}')
TYPE=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

echo "$NAME is of type $TYPE, weighs ${WEIGHT}kg, and is ${HEIGHT}m tall."
